export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const POST_ADD_SUCCESS = 'POST_ADD_SUCCESS';
export const SEARCH_USER = 'SEARCH_USER';
export const FIND_USER = 'FIND_USER';
export const POST_ALL_SUCCESS = 'POST_ALL_SUCCESS';
export const MY_BLOGPOSTS = 'MY_BLOGPOSTS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';